import type { SubtitleSegment } from "../../engine";

export const SUBTITLE_SEGMENTS: SubtitleSegment[] = [
  {
    text: "Your brain is a pathological liar when tired.",
    start: 0,
    end: 2.5,
    words: [
      { word: "Your", start: 0, end: 0.3 },
      { word: "brain", start: 0.3, end: 0.6 },
      { word: "is", start: 0.6, end: 0.8 },
      { word: "a", start: 0.8, end: 0.9 },
      { word: "pathological", start: 0.9, end: 1.5 },
      { word: "liar", start: 1.5, end: 2.0 },
      { word: "when", start: 2.0, end: 2.2 },
      { word: "tired.", start: 2.2, end: 2.5 },
    ],
  },
  {
    text: "HyperNiche tracks your sleep and cognitive performance in real time.",
    start: 2.5,
    end: 5.5,
    words: [
      { word: "HyperNiche", start: 2.5, end: 2.9 },
      { word: "tracks", start: 2.9, end: 3.2 },
      { word: "your", start: 3.2, end: 3.4 },
      { word: "sleep", start: 3.4, end: 3.7 },
      { word: "and", start: 3.7, end: 3.9 },
      { word: "cognitive", start: 3.9, end: 4.3 },
      { word: "performance", start: 4.3, end: 4.8 },
      { word: "in", start: 4.8, end: 5.0 },
      { word: "real", start: 5.0, end: 5.2 },
      { word: "time.", start: 5.2, end: 5.5 },
    ],
  },
  {
    text: "See how you stack up against the competition.",
    start: 5.5,
    end: 8,
    words: [
      { word: "See", start: 5.5, end: 5.7 },
      { word: "how", start: 5.7, end: 5.9 },
      { word: "you", start: 5.9, end: 6.1 },
      { word: "stack", start: 6.1, end: 6.4 },
      { word: "up", start: 6.4, end: 6.6 },
      { word: "against", start: 6.6, end: 7.0 },
      { word: "the", start: 7.0, end: 7.1 },
      { word: "competition.", start: 7.1, end: 8.0 },
    ],
  },
  {
    text: "Track, analyze, act, improve. That's the workflow.",
    start: 8,
    end: 11,
    words: [
      { word: "Track,", start: 8.0, end: 8.4 },
      { word: "analyze,", start: 8.4, end: 8.9 },
      { word: "act,", start: 8.9, end: 9.2 },
      { word: "improve.", start: 9.2, end: 9.7 },
      { word: "That's", start: 9.7, end: 10.0 },
      { word: "the", start: 10.0, end: 10.2 },
      { word: "workflow.", start: 10.2, end: 11.0 },
    ],
  },
  {
    text: "Reaction time tests, microsleep alerts, sleep debt calculator.",
    start: 11,
    end: 14,
    words: [
      { word: "Reaction", start: 11.0, end: 11.4 },
      { word: "time", start: 11.4, end: 11.6 },
      { word: "tests,", start: 11.6, end: 12.0 },
      { word: "microsleep", start: 12.0, end: 12.5 },
      { word: "alerts,", start: 12.5, end: 12.9 },
      { word: "sleep", start: 12.9, end: 13.2 },
      { word: "debt", start: 13.2, end: 13.5 },
      { word: "calculator.", start: 13.5, end: 14.0 },
    ],
  },
  {
    text: "Start sleeping smarter at hyperniche.app",
    start: 14,
    end: 17,
    words: [
      { word: "Start", start: 14.0, end: 14.3 },
      { word: "sleeping", start: 14.3, end: 14.7 },
      { word: "smarter", start: 14.7, end: 15.2 },
      { word: "at", start: 15.2, end: 15.4 },
      { word: "hyperniche.app", start: 15.4, end: 17.0 },
    ],
  },
];
