import type { SubtitleSegment } from "../../engine";

export const SUBTITLE_SEGMENTS: SubtitleSegment[] = [
  {
    text: "Every API deserves an app.",
    start: 0,
    end: 2,
    words: [
      { word: "Every", start: 0, end: 0.4 },
      { word: "API", start: 0.4, end: 0.8 },
      { word: "deserves", start: 0.8, end: 1.2 },
      { word: "an", start: 1.2, end: 1.5 },
      { word: "app.", start: 1.5, end: 2.0 },
    ],
  },
  {
    text: "Paste your OpenAPI URL and Floom builds the entire frontend.",
    start: 2,
    end: 4.5,
    words: [
      { word: "Paste", start: 2.0, end: 2.3 },
      { word: "your", start: 2.3, end: 2.5 },
      { word: "OpenAPI", start: 2.5, end: 2.9 },
      { word: "URL", start: 2.9, end: 3.2 },
      { word: "and", start: 3.2, end: 3.4 },
      { word: "Floom", start: 3.4, end: 3.7 },
      { word: "builds", start: 3.7, end: 4.0 },
      { word: "the", start: 4.0, end: 4.1 },
      { word: "entire", start: 4.1, end: 4.3 },
      { word: "frontend.", start: 4.3, end: 4.5 },
    ],
  },
  {
    text: "It detects your endpoints, generates pages, and wires up auth.",
    start: 4.5,
    end: 7,
    words: [
      { word: "It", start: 4.5, end: 4.7 },
      { word: "detects", start: 4.7, end: 5.0 },
      { word: "your", start: 5.0, end: 5.2 },
      { word: "endpoints,", start: 5.2, end: 5.6 },
      { word: "generates", start: 5.6, end: 6.0 },
      { word: "pages,", start: 6.0, end: 6.3 },
      { word: "and", start: 6.3, end: 6.5 },
      { word: "wires", start: 6.5, end: 6.7 },
      { word: "up", start: 6.7, end: 6.9 },
      { word: "auth.", start: 6.9, end: 7.0 },
    ],
  },
  {
    text: "Watch it stream live. Deals, contacts, pipelines — all there.",
    start: 7,
    end: 10,
    words: [
      { word: "Watch", start: 7.0, end: 7.3 },
      { word: "it", start: 7.3, end: 7.5 },
      { word: "stream", start: 7.5, end: 7.8 },
      { word: "live.", start: 7.8, end: 8.2 },
      { word: "Deals,", start: 8.2, end: 8.5 },
      { word: "contacts,", start: 8.5, end: 8.9 },
      { word: "pipelines", start: 8.9, end: 9.3 },
      { word: "—", start: 9.3, end: 9.4 },
      { word: "all", start: 9.4, end: 9.6 },
      { word: "there.", start: 9.6, end: 10.0 },
    ],
  },
  {
    text: "Plug it into Claude via MCP. One config, done.",
    start: 10,
    end: 12.5,
    words: [
      { word: "Plug", start: 10.0, end: 10.3 },
      { word: "it", start: 10.3, end: 10.5 },
      { word: "into", start: 10.5, end: 10.7 },
      { word: "Claude", start: 10.7, end: 11.0 },
      { word: "via", start: 11.0, end: 11.2 },
      { word: "MCP.", start: 11.2, end: 11.5 },
      { word: "One", start: 11.5, end: 11.8 },
      { word: "config,", start: 11.8, end: 12.1 },
      { word: "done.", start: 12.1, end: 12.5 },
    ],
  },
  {
    text: "Auth, database, storage, realtime, admin panel. Out of the box.",
    start: 12.5,
    end: 15.5,
    words: [
      { word: "Auth,", start: 12.5, end: 12.8 },
      { word: "database,", start: 12.8, end: 13.2 },
      { word: "storage,", start: 13.2, end: 13.6 },
      { word: "realtime,", start: 13.6, end: 14.0 },
      { word: "admin", start: 14.0, end: 14.3 },
      { word: "panel.", start: 14.3, end: 14.6 },
      { word: "Out", start: 14.6, end: 14.9 },
      { word: "of", start: 14.9, end: 15.1 },
      { word: "the", start: 15.1, end: 15.2 },
      { word: "box.", start: 15.2, end: 15.5 },
    ],
  },
  {
    text: "Self-host with Docker in one line.",
    start: 15.5,
    end: 17.5,
    words: [
      { word: "Self-host", start: 15.5, end: 15.9 },
      { word: "with", start: 15.9, end: 16.1 },
      { word: "Docker", start: 16.1, end: 16.5 },
      { word: "in", start: 16.5, end: 16.7 },
      { word: "one", start: 16.7, end: 17.0 },
      { word: "line.", start: 17.0, end: 17.5 },
    ],
  },
  {
    text: "Build faster at floom.io",
    start: 17.5,
    end: 20,
    words: [
      { word: "Build", start: 17.5, end: 17.8 },
      { word: "faster", start: 17.8, end: 18.2 },
      { word: "at", start: 18.2, end: 18.4 },
      { word: "floom.io", start: 18.4, end: 20.0 },
    ],
  },
];
