import type { SubtitleSegment } from "../../engine";

export const SUBTITLE_SEGMENTS: SubtitleSegment[] = [
  {
    text: "The hidden math of sleep debt.",
    start: 0,
    end: 2,
    words: [
      { word: "The", start: 0, end: 0.2 },
      { word: "hidden", start: 0.2, end: 0.5 },
      { word: "math", start: 0.5, end: 0.8 },
      { word: "of", start: 0.8, end: 1.0 },
      { word: "sleep", start: 1.0, end: 1.3 },
      { word: "debt.", start: 1.3, end: 2.0 },
    ],
  },
  {
    text: "Today we're looking at a major synthesis of research from the aviation and medical sectors.",
    start: 2,
    end: 5.5,
    words: [
      { word: "Today", start: 2.0, end: 2.3 },
      { word: "we're", start: 2.3, end: 2.5 },
      { word: "looking", start: 2.5, end: 2.8 },
      { word: "at", start: 2.8, end: 3.0 },
      { word: "a", start: 3.0, end: 3.1 },
      { word: "major", start: 3.1, end: 3.4 },
      { word: "synthesis", start: 3.4, end: 3.9 },
      { word: "of", start: 3.9, end: 4.0 },
      { word: "research", start: 4.0, end: 4.4 },
      { word: "from", start: 4.4, end: 4.6 },
      { word: "the", start: 4.6, end: 4.7 },
      { word: "aviation", start: 4.7, end: 5.1 },
      { word: "and", start: 5.1, end: 5.2 },
      { word: "medical", start: 5.2, end: 5.4 },
      { word: "sectors.", start: 5.4, end: 5.5 },
    ],
  },
  {
    text: "The question is simple: can you actually trust your brain when you're tired?",
    start: 5.5,
    end: 9,
    words: [
      { word: "The", start: 5.5, end: 5.7 },
      { word: "question", start: 5.7, end: 6.0 },
      { word: "is", start: 6.0, end: 6.2 },
      { word: "simple:", start: 6.2, end: 6.6 },
      { word: "can", start: 6.6, end: 6.8 },
      { word: "you", start: 6.8, end: 7.0 },
      { word: "actually", start: 7.0, end: 7.3 },
      { word: "trust", start: 7.3, end: 7.6 },
      { word: "your", start: 7.6, end: 7.8 },
      { word: "brain", start: 7.8, end: 8.1 },
      { word: "when", start: 8.1, end: 8.3 },
      { word: "you're", start: 8.3, end: 8.5 },
      { word: "tired?", start: 8.5, end: 9.0 },
    ],
  },
  {
    text: "Well, here's the thing. Your brain is a pathological liar.",
    start: 9,
    end: 12,
    words: [
      { word: "Well,", start: 9.0, end: 9.3 },
      { word: "here's", start: 9.3, end: 9.6 },
      { word: "the", start: 9.6, end: 9.7 },
      { word: "thing.", start: 9.7, end: 10.0 },
      { word: "Your", start: 10.0, end: 10.3 },
      { word: "brain", start: 10.3, end: 10.6 },
      { word: "is", start: 10.6, end: 10.8 },
      { word: "a", start: 10.8, end: 10.9 },
      { word: "pathological", start: 10.9, end: 11.5 },
      { word: "liar.", start: 11.5, end: 12.0 },
    ],
  },
  {
    text: "Researchers found that getting only six hours of sleep for two weeks straight makes your brain perform like you've been awake for forty-eight hours.",
    start: 12,
    end: 18,
    words: [
      { word: "Researchers", start: 12.0, end: 12.5 },
      { word: "found", start: 12.5, end: 12.8 },
      { word: "that", start: 12.8, end: 13.0 },
      { word: "getting", start: 13.0, end: 13.3 },
      { word: "only", start: 13.3, end: 13.6 },
      { word: "six", start: 13.6, end: 13.9 },
      { word: "hours", start: 13.9, end: 14.2 },
      { word: "of", start: 14.2, end: 14.3 },
      { word: "sleep", start: 14.3, end: 14.7 },
      { word: "for", start: 14.7, end: 14.9 },
      { word: "two", start: 14.9, end: 15.1 },
      { word: "weeks", start: 15.1, end: 15.4 },
      { word: "straight", start: 15.4, end: 15.8 },
      { word: "makes", start: 15.8, end: 16.1 },
      { word: "your", start: 16.1, end: 16.3 },
      { word: "brain", start: 16.3, end: 16.6 },
      { word: "perform", start: 16.6, end: 17.0 },
      { word: "like", start: 17.0, end: 17.2 },
      { word: "you've", start: 17.2, end: 17.4 },
      { word: "been", start: 17.4, end: 17.6 },
      { word: "awake", start: 17.6, end: 17.9 },
      { word: "for", start: 17.9, end: 18.0 },
      { word: "forty-eight", start: 18.0, end: 18.4 },
      { word: "hours.", start: 18.4, end: 18.8 },
    ],
  },
  {
    text: "We're talking about microsleeps, where your brain literally shuts off for half a second.",
    start: 18.8,
    end: 22.5,
    words: [
      { word: "We're", start: 18.8, end: 19.1 },
      { word: "talking", start: 19.1, end: 19.4 },
      { word: "about", start: 19.4, end: 19.7 },
      { word: "microsleeps,", start: 19.7, end: 20.3 },
      { word: "where", start: 20.3, end: 20.6 },
      { word: "your", start: 20.6, end: 20.8 },
      { word: "brain", start: 20.8, end: 21.1 },
      { word: "literally", start: 21.1, end: 21.5 },
      { word: "shuts", start: 21.5, end: 21.8 },
      { word: "off", start: 21.8, end: 22.0 },
      { word: "for", start: 22.0, end: 22.2 },
      { word: "half", start: 22.2, end: 22.4 },
      { word: "a", start: 22.4, end: 22.5 },
      { word: "second.", start: 22.5, end: 23.0 },
    ],
  },
  {
    text: "But here's the real twist. It's called the Judgment-Vigilance Dissociation.",
    start: 23,
    end: 27,
    words: [
      { word: "But", start: 23.0, end: 23.2 },
      { word: "here's", start: 23.2, end: 23.5 },
      { word: "the", start: 23.5, end: 23.6 },
      { word: "real", start: 23.6, end: 23.9 },
      { word: "twist.", start: 23.9, end: 24.3 },
      { word: "It's", start: 24.3, end: 24.6 },
      { word: "called", start: 24.6, end: 24.9 },
      { word: "the", start: 24.9, end: 25.0 },
      { word: "Judgment-Vigilance", start: 25.0, end: 25.7 },
      { word: "Dissociation.", start: 25.7, end: 27.0 },
    ],
  },
  {
    text: "While your actual performance keeps crashing, your subjective feeling of sleepiness just levels off.",
    start: 27,
    end: 31,
    words: [
      { word: "While", start: 27.0, end: 27.3 },
      { word: "your", start: 27.3, end: 27.5 },
      { word: "actual", start: 27.5, end: 27.8 },
      { word: "performance", start: 27.8, end: 28.3 },
      { word: "keeps", start: 28.3, end: 28.6 },
      { word: "crashing,", start: 28.6, end: 29.0 },
      { word: "your", start: 29.0, end: 29.2 },
      { word: "subjective", start: 29.2, end: 29.7 },
      { word: "feeling", start: 29.7, end: 30.0 },
      { word: "of", start: 30.0, end: 30.1 },
      { word: "sleepiness", start: 30.1, end: 30.5 },
      { word: "just", start: 30.5, end: 30.7 },
      { word: "levels", start: 30.7, end: 31.0 },
      { word: "off.", start: 31.0, end: 31.5 },
    ],
  },
  {
    text: "You honestly believe you've adjusted to the grind, but your reaction times say you're functionally impaired.",
    start: 31.5,
    end: 36,
    words: [
      { word: "You", start: 31.5, end: 31.7 },
      { word: "honestly", start: 31.7, end: 32.1 },
      { word: "believe", start: 32.1, end: 32.5 },
      { word: "you've", start: 32.5, end: 32.8 },
      { word: "adjusted", start: 32.8, end: 33.2 },
      { word: "to", start: 33.2, end: 33.4 },
      { word: "the", start: 33.4, end: 33.5 },
      { word: "grind,", start: 33.5, end: 33.9 },
      { word: "but", start: 33.9, end: 34.1 },
      { word: "your", start: 34.1, end: 34.3 },
      { word: "reaction", start: 34.3, end: 34.7 },
      { word: "times", start: 34.7, end: 35.0 },
      { word: "say", start: 35.0, end: 35.2 },
      { word: "you're", start: 35.2, end: 35.4 },
      { word: "functionally", start: 35.4, end: 35.9 },
      { word: "impaired.", start: 35.9, end: 36.5 },
    ],
  },
  {
    text: "So never trust your own vibe after a late night. Just go to bed.",
    start: 36.5,
    end: 41,
    words: [
      { word: "So", start: 36.5, end: 36.7 },
      { word: "never", start: 36.7, end: 37.0 },
      { word: "trust", start: 37.0, end: 37.3 },
      { word: "your", start: 37.3, end: 37.5 },
      { word: "own", start: 37.5, end: 37.7 },
      { word: "vibe", start: 37.7, end: 38.0 },
      { word: "after", start: 38.0, end: 38.3 },
      { word: "a", start: 38.3, end: 38.4 },
      { word: "late", start: 38.4, end: 38.7 },
      { word: "night.", start: 38.7, end: 39.1 },
      { word: "Just", start: 39.1, end: 39.4 },
      { word: "go", start: 39.4, end: 39.6 },
      { word: "to", start: 39.6, end: 39.7 },
      { word: "bed.", start: 39.7, end: 41.0 },
    ],
  },
];
